print('What do you get when you cross a snowman whit vampire?')
input()
print('Frostbite!')
print()
print('What do dentists call an astronaut\'s cavity?')
input()
print('A black hole!')
print()
print('Knock knock.')
input()
print("Who's there?")
input()
print('interrupting cow.')
input()
print('interrupting cow wh', end='')
print('-MOO!')
